grails-app/controllers/br/unirn/projeto20151/security/SecureController.groovy
package br.unirn.projeto20151.security

import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
class SecureController {

//    static scaffold = true

    def springSecurityService

    @Secured(['ROLE_ADMIN'])
    def index() {
        render "Apenas pessoal autorizado"
    }

    @Secured(['ROLE_PARENT', 'ROLE_CHILD', 'ROLE_ADMIN'])
    def logout(){
        session?.invalidate()
        redirect uri: '/'
    }

}

grails-app/views/layouts/_leftBar.gsp
<!-- Left side column. contains the logo and sidebar -->

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        %{--<div class="user-panel">
            <div class="pull-left image">
                <asset:image src="user2-160x160.jpg" class="img-circle" alt="User Image"/>
                --}%%{--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />--}%%{--
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>--}%
        <!-- search form -->
        %{--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>--}%
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
        <li class="header">MENU</li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-rocket"></i> <span>Postagens</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><g:link controller="postagem" action="meusPosts"> <i class="fa fa-circle-o"></i> Meus Posts </g:link></li>
                <li><g:link controller="postagem" action="create"> <i class="fa fa-circle-o"></i> Cadastrar Post </g:link></li>
                <li><g:link controller="postagem" action="buscar"> <i class="fa fa-circle-o"></i> Buscar Post </g:link></li>
                %{--<li>
                    <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                        <li>
                            <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>--}%
            </ul>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-smile-o"></i> <span>Família</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><g:link controller="familia" action="myFamily"><i class="fa fa-circle-o"></i> Minha Família </g:link></li>
                <li><g:link controller="user" action="myProfile"><i class="fa fa-circle-o"></i> Meu Perfil </g:link></li>

                <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_PARENT">
                    <li><g:link controller="familia" action="gerenciar"><i class="fa fa-circle-o"></i> Gerenciar </g:link></li>
                    <li><g:link controller="familia" action="itensBloqueados"><i class="fa fa-circle-o"></i> Itens Bloqueados </g:link></li>
                </sec:ifAnyGranted>

            </ul>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-list"></i> <span>Categorias</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><g:link controller="categoria" action="index"><i class="fa fa-circle-o"></i> Gerenciar Categorias </g:link></li>
                </sec:ifAnyGranted>
                <li><g:link controller="categoria" action="listar"><i class="fa fa-circle-o"></i> Listar Categorias </g:link></li>

            </ul>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-tags"></i> <span>Tags</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><g:link controller="tag" action="index"><i class="fa fa-circle-o"></i> Gerrenciar Tags </g:link></li>
                </sec:ifAnyGranted>
                <li><g:link controller="tag" action="listar"><i class="fa fa-circle-o"></i> Listar Tags</g:link></li>
                <li><g:link controller="tag" action="ultimasTags"><i class="fa fa-circle-o"></i> Últimas Tags</g:link></li>
                <li><g:link controller="tag" action="tagsMaisUsadas"><i class="fa fa-circle-o"></i> Tags Mais Usadas</g:link></li>
                <li><g:link controller="tag" action="buscarTag"><i class="fa fa-circle-o"></i> Buscar por Tag </g:link></li>

            </ul>
        </li>



        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-danger"></i> Important</a></li>
        <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Warning</a></li>
        <li><a href="#"><i class="fa fa-circle-o text-info"></i> Information</a></li>
    </ul>
    </section>
    <!-- /.sidebar -->
</aside>

grails-app/views/layouts/_topBar.gsp
<%@ page import="br.unirn.projeto20151.security.User" %>

<header class="main-header">
    <!-- Logo -->
    <g:link uri="/" class="logo"><b>Vida em Família</b></g:link>
    %{--<a href="index2.html" class="logo"><b>Admin</b>LTE</a>--}%
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <sec:ifLoggedIn>
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        </sec:ifLoggedIn>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <sec:ifLoggedIn>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-users text-red"></i> 5 new members joined
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-user text-red"></i> You changed your username
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">View all</a></li>
                        </ul>
                    </li>
                </sec:ifLoggedIn>

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        %{--<asset:image src="user2-160x160.jpg" class="user-image" alt="User Image"/>--}%
                        <span class="hidden-xs">Minha Conta</span>
                    </a>
                    <ul class="dropdown-menu">

                        <sec:ifNotLoggedIn>
                            <!-- User image -->
                            <li class="user-header">
                                %{--<asset:image src="user2-160x160.jpg" class="img-circle" alt="User Image"/>--}%
                                <i class="fa fa-user fa-4x" ></i>
                                <p>
                                    Área de Usuários
                                    <small>Perfil, Autenticação e Cadastro</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-6 text-center">
                                    <g:link controller="login" action="auth" class="btn btn-flat btn-primary"> Entrar </g:link>
                                </div>
                                <div class="col-xs-6 text-center">
                                    <g:link controller="user" action="create" class="btn btn-flat btn-warning"> Cadastrar</g:link>
                                </div>
                            </li>
                        </sec:ifNotLoggedIn>

                        <sec:ifLoggedIn>
                            <!-- User image -->
                            <li class="user-header">
                                <i class="fa fa-user fa-4x" ></i>
                                <p>
                                    <sec:loggedInUserInfo field="username"/>
                                    %{--Área de Usuários--}%
                                    <small>Perfil, Autenticação e Cadastro</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-12 text-center">
                                    <g:link controller="familia" action="myFamily" class="btn btn-block btn-default btn-flat"> Minha Família </g:link>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <g:link controller="user" action="myProfile" class="btn btn-flat btn-primary"> Meu Perfil </g:link>
                                </div>
                                <div class="pull-right">
                                    <g:link controller="secure" action="logout" class="btn btn-danger btn-flat"
                                    > Sair </g:link>
                                </div>
                            </li>
                        </sec:ifLoggedIn>

                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

grails-app/views/layouts/bak_main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="AdminLTE 2 | Dashboard"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
    <asset:stylesheet src="application.css"/>
    <asset:javascript src="application.js"/>

    <g:layoutHead/>

<!-- Ionicons 2.0.0 -->
%{--<link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />--}%
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
%{--<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>--}%
%{--<![endif]-->--}%

</head>

<body id="layoutMainBodyId" class="skin-blue">
<sec:ifNotLoggedIn>
    <script>
        console.log("usuario nao logado...");
        $("#layoutMainBodyId").addClass("sidebar-collapse");
    </script>
</sec:ifNotLoggedIn>

<div class="wrapper">

    <g:render template="/layouts/topBar"/>

    <sec:ifLoggedIn>
        <g:render template="/layouts/leftBar"/>
    </sec:ifLoggedIn>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <div id="pageBodyId">
            <g:layoutBody/>
        </div>
    </div>

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Versão</b> 1.0
        </div>
        <strong>Copyright &copy; 2015 <a href="javascript:;">bsi-unirn</a>.</strong> All rights reserved.
    </footer>
</div><!-- ./wrapper -->


</body>
</html>